<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppAlert from '../components/AppAlert.vue'
import DataState from '../components/DataState.vue'
import ConfirmationModal from '../components/ConfirmationModal.vue'
import { actionLabels, entityLabels, getAuditLogs, undoAuditLog, type AuditLog } from '../services/auditLogService'

const route = useRoute(); const router = useRouter(); const log = ref<AuditLog | null>(null); const loading = ref(true); const errorMessage = ref(''); const showUndo = ref(false); const undoing = ref(false)
const oldValues = computed(() => parse(log.value?.oldValues)); const newValues = computed(() => parse(log.value?.newValues))
function parse(value?: string | null) { if (!value) return null; try { return JSON.parse(value) as Record<string, unknown> } catch { return { Değer: value } } }
function formatDate(value: string) { return new Intl.DateTimeFormat('tr-TR', { timeZone: 'Europe/Istanbul', dateStyle: 'long', timeStyle: 'medium' }).format(new Date(value)) }
function entityRoute(item: AuditLog) { if (item.entityType === 'Device') return { name: 'device-detail', params: { id: item.entityId } }; if (item.entityType === 'Personnel') return { name: 'personnel-detail', params: { id: item.entityId } }; return null }
async function load() { loading.value = true; try { const logs = await getAuditLogs(); log.value = logs.find(item => item.id === route.params.id) ?? null; if (!log.value) errorMessage.value = 'Hareket kaydı bulunamadı.' } catch (error: unknown) { errorMessage.value = error instanceof Error ? error.message : 'Hareket yüklenemedi.' } finally { loading.value = false } }
async function undo() { if (!log.value) return; undoing.value = true; try { await undoAuditLog(log.value.id); showUndo.value = false; await load() } catch (error: unknown) { errorMessage.value = error instanceof Error ? error.message : 'İşlem geri alınamadı.' } finally { undoing.value = false } }
onMounted(load)
</script>

<template><section class="audit-detail-page"><button class="btn btn-light border mb-3" type="button" @click="router.push({ name: 'activity' })"><i class="bi bi-arrow-left me-2"></i>Son Hareketlere Dön</button><DataState v-if="loading" type="loading" title="Hareket yükleniyor" /><AppAlert v-else-if="errorMessage" variant="danger">{{ errorMessage }}</AppAlert><template v-else-if="log"><header class="inventory-page-hero"><span class="inventory-page-hero__visual"><i class="bi bi-clock-history"></i></span><div class="inventory-page-hero__main"><span class="inventory-page-hero__eyebrow">İŞLEM DETAYI</span><h1 class="inventory-page-hero__title">{{ log.description }}</h1><p class="inventory-page-hero__description">{{ formatDate(log.createdAt) }} · {{ log.userDisplayName }}</p></div><button v-if="log.canUndo" class="btn btn-warning" type="button" @click="showUndo = true"><i class="bi bi-arrow-counterclockwise me-2"></i>Geri Al</button></header><div class="audit-detail-grid"><article class="dashboard-panel"><span class="section-kicker">KAYIT BİLGİSİ</span><dl class="detail-grid mt-3 mb-0"><div><dt>İşlem</dt><dd>{{ actionLabels[log.actionType] ?? log.actionType }}</dd></div><div><dt>Kayıt türü</dt><dd>{{ entityLabels[log.entityType] ?? log.entityType }}</dd></div><div><dt>Kayıt ID</dt><dd><code>{{ log.entityId }}</code></dd></div><div><dt>Durum</dt><dd>{{ log.undoneAt ? 'Geri alınmış' : log.canUndo ? 'Geri alınabilir' : 'Bilgi kaydı' }}</dd></div></dl><RouterLink v-if="entityRoute(log)" :to="entityRoute(log)!" class="btn btn-outline-primary mt-3"><i class="bi bi-box-arrow-up-right me-2"></i>Etkilenen Kaydı Aç</RouterLink></article><article class="dashboard-panel"><span class="section-kicker">DEĞİŞİKLİKLER</span><div class="audit-values-grid"><section><h2>Önceki Değerler</h2><pre>{{ oldValues ? JSON.stringify(oldValues, null, 2) : '—' }}</pre></section><section><h2>Yeni Değerler</h2><pre>{{ newValues ? JSON.stringify(newValues, null, 2) : '—' }}</pre></section></div></article></div></template><ConfirmationModal :show="showUndo" title="İşlem geri alınsın mı?" message="Mevcut kayıt durumu doğrulanacak ve yalnızca güvenliyse geri alınacaktır." :detail="log?.description ?? ''" :confirming="undoing" :error-message="errorMessage" confirm-label="Geri Al" @cancel="showUndo = false" @confirm="undo" /></section></template>
